version: '3'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    container_name: mysql
    hostname: mysql
    volumes:
      - ./setup/mysql/conf.d:/etc/mysql/conf.d
      - ./setup/mysql/init:/docker-entrypoint-initdb.d

  python:
    build: .
    container_name: python
    links:
      - mysql
    tty: true
    environment:
      MYSQL_HOST: mysql
    volumes:
      # 面倒なのでプロジェクトごと共有する
      - ../csv_to_db:/csv_to_db
